Repository wanted-pre-onboarding-team-12th-7/pre-onboarding-12th-3-7, pull requests merged in 2023-09, with the labels that each got.

#3 feat: setting router and pages
  package-lock.json
  package.json
  src/App.tsx
  src/pages/MainPage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/PageRouter.tsx
Labels: feat

#7 feat: #6 검색 컴포넌트 생성 및 마크업
  src/App.tsx
  src/components/search/SearchForm.tsx
  src/components/search/SearchSuggestion.tsx
  src/components/search/type.ts
  src/pages/MainPage.tsx
  src/pages/PageRouter.tsx
Labels: feat

#8 feat: #2 axiosInstance 초기화 & suggestion get API 함수 추가
  package-lock.json
  package.json
  src/apis/index.ts
  src/apis/instance.ts
  src/apis/suggestion.ts
Labels: feat

#10 feat: #9 useDebounce 커스텀 훅 제작
  src/apis/suggestion.ts
  src/components/search/SearchSuggestion.tsx
  src/hooks/useDebounce.ts
  src/hooks/useSuggestions.ts
Labels: feat

#12 feat: #11 API 호출별 로컬 캐싱 구현
  src/hooks/useSuggestions.ts
  src/store/CacheRepository.ts
  tsconfig.json
Labels: feat

#15 refactor: #14 캐싱 관심사 분리
  src/apis/suggestion.ts
  src/hooks/useSuggestions.ts
Labels: refactor

#16 feat: #13 키보드로 검색결과 이동
  src/components/search/SearchForm.tsx
  src/components/search/SearchSuggestion.tsx
  src/components/search/type.ts
  src/hooks/useKeyboardNavigation.ts
  src/pages/MainPage.tsx
Labels: feat

#18 style: #17 style clone
  public/index.html
  public/manifest.json
  src/components/search/Search.styled.ts
  src/components/search/SearchForm.tsx
  src/components/search/SearchSuggestion.styled.ts
  src/components/search/SearchSuggestion.tsx
  src/components/search/type.ts
  src/hooks/useKeyboardNavigation.ts
  src/pages/MainPage.tsx
  src/styles/base/GlobalStyles.ts
  src/styles/base/styled.d.ts
  src/styles/constants/color.ts
  src/styles/constants/fontsize.ts
  src/styles/svg/buttonSearchIcon.svg
  src/styles/svg/clearIcon.svg
  src/styles/svg/placeholderSearchIcon.svg
Labels: style

#20 fix: #19 macOS에서 onKeyDown이 2번 발생하는 문제 해결
  src/hooks/useKeyboardNavigation.ts
Labels: bug

#23 style: props명에 $를 붙여주어 styled-components에서 transient props로 인식하게 수정
  src/components/search/Search.styled.ts
  src/components/search/SearchForm.tsx
  src/components/search/SearchSuggestion.styled.ts
  src/components/search/SearchSuggestion.tsx
Labels: style

#29 style: add svg images
  src/assets/svg/centerImage.svg
  src/assets/svg/leftImage.svg
  src/assets/svg/rightImage.svg
  src/components/search/Search.styled.ts
  src/components/search/SearchSvgImages.tsx
  src/pages/MainPage.tsx
Labels: style
